inherit_from: .rubocop_airbnb.yml

require:
  - rubocop-rails

inherit_from:
  - .rubocop_airbnb.yml

Rails:
   Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - 'spec/**/*'
    - '.git/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/uploaders/image_uploader.rb'
    - 'app/models/*'
    - 'app/controllers/reservations_controller.rb'
    
    
  DisplayCopNames: true
  TargetRubyVersion: 2.6

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/AbcSize:
  Max: 970

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Metrics/MethodLength:
  Max: 1100
  Exclude:
    - "db/migrate/*.rb"