version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: bundle exec rails s -p 3002 -b '0.0.0.0'
    volumes:
      - .:/myapp
    environment: 
    - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    ports:
      - "3002:3002"
    depends_on:
      - db
      - chrome
  chrome:
    image: selenium/standalone-chrome-debug:latest
    shm_size: 256m
    ports:
      - 4444:4444
      - 5900:5900
