version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/kouchbento
    steps:
      - checkout:
          path: ~/kouchbento
      - ruby/install-deps

  rspec:
    docker:
      - image: circleci/ruby:2.7-node-browsers #-browsersをつける事でsystemsspecが動く？#
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_DATABASE: myapp_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "%"
      RAILS_ENV: test
    working_directory: ~/kouchbento
    steps:
      - checkout:
          path: ~/kouchbento
      - run:
         command: chromedriver
         background: true
      - run: bundle install --no-deployment
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: yarn Install
          command: yarn install --ignore-engines
      - run: bundle exec bin/webpack
      - run:
          name: test
          command: bundle exec rspec
    
  deploy:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker 
          command: bundle update --bundler
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME
 
workflows:
  version: 2
  circleci:
    jobs:
      - build
      - rspec
      - deploy:
          requires:
            - build
            - rspec
    
