version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/kouchdelivery
    steps:
      - checkout:
          path: ~/kouchdelivery
      - run: bundle install --no-deployment

  rubocop:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.5
        environment:
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: myapp_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: rubocop
    working_directory: ~/kouchdelivery
    steps:
        - checkout
        - run: 
            name: Install bundler:1.16.6
            command: gem install bundler:1.16.6
        - run: 
            name: gem installation
            command: bundle install
        - run:
            name: Echo Test
            command: bundle exec rubocop

  rspec:
    docker:
      - image: circleci/ruby:2.7-node-browsers
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_DATABASE: myapp_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
    working_directory: ~/kouchbento
    steps:
      - checkout:
          path: ~/kouchbento
      - run:
         command: chromedriver
         background: true
      - run: 
          name: Get the necessary gem(s)
          command: bundle install --no-deployment
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: yarn Install
          command: yarn install --ignore-engines
      - run: 
          name: Installing webpack
          command: bundle exec bin/webpack
      - run:
          name: test
          command: bundle exec rspec
    
  deploy:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker 
          command: bundle update --bundler
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME
 
workflows:
  version: 2
  circleci:
    jobs:
      - build
      - rubocop
      - rspec
      - deploy:
          requires:
            - build
            - rubocop
            - rspec
    
